### PR TITLE
Add UI Buttons with CSS

### PR DESCRIPTION
**Pull request by alshakero**
I also modified the CSS a little bit to look better.

### CODE REVIEW

**Comment by tomalec** [comment]
Could you make a separate branch for this issue and PR it to visual-editor branch?

**Comment by tomalec** [comment]
We already found font icons problematic, have you considered SVG?
http://ianfeather.co.uk/ten-reasons-we-switched-from-an-icon-font-to-svg/
https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/
https://github.com/blog/2112-delivering-octicons-with-svg

**Comment by alshakero** [comment]
@tomalec Changed icons to SVG and PRed to visual editor.

**Comment by tomalec** [comment]
Closing in favor of https://github.com/Starcounter/starcounter-layout-html-editor/pull/9

**Pull request closed without merging**
