### PR TITLE
Support starcounter-include 3.x

### PR DESCRIPTION
**Pull request by tomalec**
Support Starcounter/starcounter-include@3.0.0
remove juicy-composition related code

### CODE REVIEW

**Comment by tomalec** [comment]
Demo requires https://github.com/Starcounter/starcounter-include/pull/47

**Comment by warpech** [comment]
I am testing this by:

1. Run KitchenSink
2. Run CompositionProvider
3. In CompositionEditor, `cd src/CompositionEditor`
4. `bower install starcounter-include#fix-aliasing-viewModel`
5. `bower install starcounter/starcounter-layout-html-editor#starcounter-include-3.x`
6. Run CompositionEditor
7. Go to `localhost:8080/kitchensink` and try editing

**Comment by warpech** [comment]
The above steps do not work for the reasons explained in https://github.com/Starcounter/starcounter-include/issues/48. 

I have problem testing it with Products as well... My versions are:

```
starcounter-layout-html-editor@521fc5ea88
starcounter-include@8ada536b68
```

Verified using Starcounter Debug Aid > Imports > Show Bower versions.

The "Add product" page does not show up.

2017-07-27 12_02_33-products

**Comment by warpech** [comment]
Ping

**Comment by tomalec** [comment]
Sorry, Products had missing few explicit slot elements as well 
https://github.com/StarcounterApps/Products/pull/59 fixes that.

**Comment by Mihaiii** [comment]
> I am testing this by:
> 
> Run KitchenSink
> Run CompositionProvider
> In CompositionEditor, cd src/CompositionEditor
> bower install starcounter-include#fix-aliasing-viewModel
> bower install starcounter/starcounter-layout-html-editor#starcounter-include-3.x
> Run CompositionEditor
> Go to localhost:8080/kitchensink and try editing

Thank you for this, it solves #15 .

> Sorry, Products had missing few explicit slot elements as well
> StarcounterApps/Products#59 fixes that.

There are more apps that have missing explicit slot elements.
In https://github.com/Starcounter/RebelsLounge/issues/152 I only dealt with "making sure that every slot="foo" is in Declarative Shadow DOM" (and the other way around).

Is it needed/mandatory to not have "missing slots" ?

**Comment by tomalec** [comment]
Sure, there are more I just thought we will migrate all the apps once we settle on functionality of the `sc-include` and Editors, as currently we are adapting all apps to not approved feature set. There is no PR to Starcoutner to merge it yet. I would migrate all our apps, docs and write a blog post only once it's there. Not to introduce cognitive load of refactoring all the views for theoretically unstable reason.


> It is needed/mandatory to not have "missing slots", right?

It's not as long as you are fine with the fact all your elements will be blendable as one big bulk of "elements with missing/empty slot attribute"

**Comment by tomalec** [comment]
The workflow to adapt all the apps before changing any of frameworkish elements, would mean to use dozens of branches in **all** our (and probably not only our) repos. Then maintaining those nbranches by the same person that makes the changes to the single element at the very end of our food chain.

repolepsy * branchitis => mental disorder (at least for me)

Not to mention that changing element such as `imported-tempalte` already require to maintain branches in ca. 4-6 repos.

Maybe we can agree that there is only one app that we could prepare to the new (app-affecting) change before propagating it to the Starcounter's `/sys` folder?

**Comment by warpech** [comment]
> Maybe we can agree that there is only one app that we could prepare to the new (app-affecting) change before propagating it to the Starcounter's `/sys` folder?

`develop` branch in sample apps should always work with the current Starcounter RC, meaning that if we release a change in Starcounter's `/sys` folder, we should update the apps within the day.

To make testing easier, maybe the branch https://github.com/Starcounter/level1/tree/starcounter-include-CEv1 can be shipped in two steps? First, ship changes to the file https://github.com/Starcounter/level1/blob/d2218dc4d433395f44da91a4d13931f27d9bbcb4/src/Starcounter/Apps/OntologyAndOrdinaryMapping.cs. Secondly, ship `starcounter-include` 3.0.0.

If not, then we should work on custom branches in the apps and a custom build of Starcounter.

**Comment by tomalec** [comment]
> meaning that **if we release a change in Starcounter's `/sys`**

As stated above, this PR is **not** for Starcounter's `/sys` folder yet.

**Comment by warpech** [comment]
I know, but can you then explain your question from the end of https://github.com/Starcounter/starcounter-layout-html-editor/pull/14#issuecomment-320306286?

I tested again with the following steps:

1. Install Starcounter 2.3.1.6924
1. Run KitchenSink (`develop`)
1. Run CompositionProvider (`develop`)
1. In CompositionEditor (`develop`), `cd src/CompositionEditor`
1. `bower install starcounter-include#master`
1. `bower install starcounter/starcounter-layout-html-editor#starcounter-include-3.x`
1. Run CompositionEditor
1. Go to `localhost:8080/kitchensink` and try editing

Editing a layout in KitchenSink worked OK!

**Comment by tomalec** [comment]
> I know, but can you then explain your question from the end of https://github.com/Starcounter/starcounter-layout-html-editor/pull/14#issuecomment-320306286?

Briefly, what I thought about is that we will agree, that:

In regards of any element/library shared across all apps and/or deeply tangled to our frontend frame, we will:
1. Branch respective element's repo,
2. Make sure tests are passing there and the change makes sense for the elemnt on its own,
   - element tests,
   - tattoo if we have one,
3. If change requires changes in apps,
   1. make a branch and adapt **only one** app - Kitchen Sink,
   2. once it passes, merge and release version of element/package,
   3. prepare a PR to Starcounter,
   4. adapt all remaining apps.
4. Run tests in TC.

**Comment by warpech** [comment]
Oh yeah, with that I completely agree. Should we make a page about this in https://github.com/starcounter/guidelines?

**Comment by tomalec** [comment]
> Should we make a page about this in https://github.com/starcounter/guidelines?

Deffinitely. But where precisely? As a new page in root level of TOC: "Workflow for shared frontend elements & packages?"

**Comment by warpech** [comment]
I agree with the root level. Maybe a shorter title, e.g. "Workflow for client-side packages".

This also affects packages like `juicy-markdown-tabbededitor`, etc.

**Comment by Mihaiii** [comment]
Maybe I'm doing something wrong here, but I have a problem on Chrome with this branch relating the highlight.
What I did:
1. Use SC version 2.3.1.6993
2. Run CompositionProvider
3. In CompositionEditor, `cd src/CompositionEditor`
4. `bower install starcounter-include#fix-aliasing-viewModel`
5. `bower install starcounter/starcounter-layout-html-editor#starcounter-include-3.x`
6. Run CompositionEditor app
7. Run SignIn app
8. Run Website app
9. Run SampleWebsiteTheme app

Target `[slot="samplewebsitetheme/main"]` within `starcounter-layout-html-editor`.

On Firefox I get:
ff-highlight

On Chrome I get:
chrome-highlight

Am I doing something wrong?

**Comment by tomalec** [comment]
Guidelines are addressed at https://github.com/Starcounter/Guidelines/pull/47

**Comment by tomalec** [comment]
@Mihaiii  what exactly is the problem, lack of highlight for the partial?

**Comment by Mihaiii** [comment]
That seems to be the only problem, yes.

**Comment by tomalec** [comment]
It seems to be fixed with the lates Starcounter build 
editor2

**Pull request merged**
